// integracao-vue/src/components/Contador.vue
<template>
    <div>
        <h1>Contador</h1>
        <h2>{{ valor }}</h2>
        <button @click="detValor(-1)">Dec</button>
        <button @click="setValor(1)">Inc</button>
    </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue'

export default defineComponent({
    props: {
        valorInicial : {
          type: Number
        } 
    },  
    setup(props: any) {
        let valor = ref(props.valorInicial || 0)
        function setValor() {
            valor.value++
        }
        function detValor() {
            valor.value--
        }

        return { setValor, valor, detValor }
    }
})
</script>

<style></style>

// integracao-react/src/components/Contador.tsx
import React, { Component } from 'react';
import ContadorValor from './ContadorValor';
import logRender from '../decorators/logRender';

interface ContadorProps {
    valorInicial?: number
}

interface ContadorState {
    valor: number
}

@logRender
export default class Contador extends Component<ContadorProps, ContadorState> {

    public state = { valor: this.props.valorInicial || 0}

    private setValor = (delta: number) => {
        this.setState({
            valor: this.state.valor + delta
        })
    }

    render(){
        return(
            <div>
                <ContadorValor contador={this.state.valor} />
                <button onClick={() => this.setValor(10)}>+</button>
                <button onClick={() => this.setValor(-10)}>-</button>
            </div>
        )
    }
}
